apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arbitcrypto-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - arbitcrypto.xyz
      secretName: arbitcrypto.xyz-tls
    - hosts:
        - api.arbitcrypto.xyz
      secretName: api.arbitcrypto.xyz-tls
  rules:
    - host: arbitcrypto.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
    - host: api.arbitcrypto.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 80
